### ISSUE TITLE
好像有错别字

### ISSUE THREAD

**Issue by lpslpsl** [guoxiaoxing/android-open-source-project-analysis#13]
导读，设计模式。那里是不是某种打成谋者了。

**Comment by imknown** [comment]
https://github.com/guoxiaoxing/android-open-source-project-analysis/blame/master/doc/%E5%AF%BC%E8%AF%BB.md#L28

这行吧

**Comment by guoxiaoxing** [comment]
已修改，在校对文章，可以关注新项目https://github.com/BeesAndroid/BeesAndroid
