### ISSUE TITLE
如何调试aosp项目中c c++部分的代码

### ISSUE THREAD

**Issue by edidada** [guoxiaoxing/android-open-source-project-analysis#16]
app开发中使用ndk开发，可以使用lldb来调试。aosp中java部分的代码，可以导入android studio中调试。但，如何使用gdb lldb来调试c c++代码呢？目前我没有找到调试c c++代码的部分，请知道的朋友告知下。
老罗《安卓源码情景分析》书中介绍了打印日志来调试，我感觉打印日志没有直接调试来的方便。
博客http://0xcc0xcd.com/p/videos/debug-aosp.php 介绍了java c++打印函数调用栈的方法 c的函数调用信息如何打印出来。

**Comment by edidada** [comment]
也许gdb和lldb这两个工具可以，但是我觉得没有达到类似as直接调试aosp中java代码的效果。

**Comment by guoxiaoxing** [comment]
参考这篇文章：https://zhuanlan.zhihu.com/p/24867284
