### ISSUE TITLE
源码下载了2/3，下载不了了

### ISSUE THREAD

**Issue by TMLAndroid** [guoxiaoxing/android-open-source-project-analysis#20]
报的这个错误   
`error: prebuilts/gradle-plugin/: platform/prebuilts/gradle-plugin checkout 2ad923bbd8c43e9da0d3edc3253fc80e64d7868b`
重试了几次都不行

**Comment by guoxiaoxing** [comment]
光从这个log看不出有什么问题，可以去问问群里的小伙伴，有没有人遇到过。
