### ISSUE TITLE
安卓使用了OkHttp，项目再使用它，为什么不会冲突

### ISSUE THREAD

**Issue by Xiue233** [guoxiaoxing/android-open-source-project-analysis#34]
安卓内使用了okhttp，没有修改过包名，但是我们的项目依然可以依赖并使用okhttp，我想请教下，这两者为什么不会冲突？

比如Apache Http，如果我们自己在项目内依赖它，APP就会在运行的时候报错。

**Comment by telyo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by telyo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
