### ISSUE TITLE
貌似还有一个地方的字写错了

### ISSUE THREAD

**Issue by adonis-lsh** [guoxiaoxing/android-open-source-project-analysis#4]
![image](https://user-images.githubusercontent.com/20501172/36708562-8df40948-1bae-11e8-8064-ca3136435855.png)

**Comment by adonis-lsh** [comment]
![image](https://user-images.githubusercontent.com/20501172/36708725-5c01fa70-1baf-11e8-8d16-efda7b2db1ad.png)

**Comment by guoxiaoxing** [comment]
谢谢指出，部分文章还有没有校对完成，后续会做改进。另外，Android是一个庞大的系统，做分析的时候难免有纰漏之处，已经建立了微信群和QQ群，后续会组织大家一起来做这个事情，毕竟一个人的力量是有限的。敬请关注~
